export const GESTION_TIPO_CONTRATO    = 'GESTION_TIPO_CONTRATO';
export const GESTION_ROLES            = 'GESTION_ROLES';
export const GESTION_ROL_PERMISOS     = 'GESTION_ROL_PERMISOS';
export const GESTION_USUARIO          = 'GESTION_USUARIO';
export const GESTION_PROCESOS         = 'GESTION_PROCESOS';
export const GESTION_TIPO_DOCUMENTOS  = 'GESTION_TIPO_DOCUMENTOS';
export const GESTION_MEDIO_PAGO       = 'GESTION_MEDIO_PAGO';
export const GESTION_TIPO_PAGO        = 'GESTION_TIPO_PAGO';
export const GESTION_TIPO_TRANSACCION = 'GESTION_TIPO_TRANSACCION';
export const GESTION_PAGO_NOMINA      = 'GESTION_PAGO_NOMINA';
export const GESTION_COMPETENCIA      = 'GESTION_COMPETENCIA'; 
//se crea constante exportable de COMPETENCIA

